// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuILgQuSMPUbp3Bf1BLkmCrjm47SZ8vFw',
    appId: '1:860043783859:web:220b95113a270dc6be8ac6',
    messagingSenderId: '860043783859',
    projectId: 'sii-admision-uth',
    authDomain: 'sii-admision-uth.firebaseapp.com',
    storageBucket: 'sii-admision-uth.firebasestorage.app',
    measurementId: 'G-KC2RXG5BK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpwfeNVFhok0UTm7AY4dw3FhjzqWwql98',
    appId: '1:860043783859:android:3f7539689fc8b246be8ac6',
    messagingSenderId: '860043783859',
    projectId: 'sii-admision-uth',
    storageBucket: 'sii-admision-uth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6i-U1kpmaub_vZlVXPhVWYH4vBGiGGPM',
    appId: '1:860043783859:ios:0528e180cbe927b8be8ac6',
    messagingSenderId: '860043783859',
    projectId: 'sii-admision-uth',
    storageBucket: 'sii-admision-uth.firebasestorage.app',
    iosBundleId: 'com.example.siiadmision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6i-U1kpmaub_vZlVXPhVWYH4vBGiGGPM',
    appId: '1:860043783859:ios:0528e180cbe927b8be8ac6',
    messagingSenderId: '860043783859',
    projectId: 'sii-admision-uth',
    storageBucket: 'sii-admision-uth.firebasestorage.app',
    iosBundleId: 'com.example.siiadmision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuILgQuSMPUbp3Bf1BLkmCrjm47SZ8vFw',
    appId: '1:860043783859:web:cb9cd251561473c6be8ac6',
    messagingSenderId: '860043783859',
    projectId: 'sii-admision-uth',
    authDomain: 'sii-admision-uth.firebaseapp.com',
    storageBucket: 'sii-admision-uth.firebasestorage.app',
    measurementId: 'G-L92C76GHNE',
  );
}
